data_pth: "M:/26_HE/01_Childcare/Data"

port: "http://127.0.0.1:5000/"

data_pths:
  in_pth: "M:/26_HE/01_Childcare/Data_Curated"
  out_pth: "M:/26_HE/01_Childcare/Data_Current"

data_in_names:
  nber: "sf12010tractdistance25miles.csv"
  acf: "acf-801-q{qtr}-2018-twc.xlsx"
  ccl: "hhsc_ccl.csv"
  kinder_neighborhoods: "tract_neighborhood_xwalk.csv"
  tract_shape: "tract_shape.csv"
  zip_shape: "zip_shape.csv"
  state_fips_state_name_xwalk: "state_fips_state_name_xwalk.csv"
  census:
    year: 2018
    est_year: 5 #options are 1, 3, 5
    subject: ["S0601", "S1201", "S1501", "S1901", "S1902"]
    detail: ["B17024", "B17026", "B17010A", "B17010B", 
             "B17010C", "B17010D", "B17010E", "B17010F",
             "B17010G", "B17010H", "B17010I"]
  poverty_threshold: "poverty_threshold_2019.xlsx"

data_out_names:
  acf_all: "acf_2018.csv"
  tracts_xwalk: "tracts_xwalk.csv"
  ccl: "hhsc_ccl.csv"
  family_prvdr_zip: "family_prvdr_zip.csv"
  osrm: "prvdr_family_commute_duration.csv"
  geocode: "mapquest_geocode.csv"
  
pkg: ["dplyr", "tidyr", "httr", "plyr", "magrittr", "Hmisc", "osrm", "rvest", "xml2", "assertthat", "readr", "readxl", "stringr", "tigris", "future.apply", "future", "parallel"]
